[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "luckypass"
version = "0.1.3"
description = "A CLI tool for auditing password strength"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name = "brklemens"}
]

[project.scripts]
luckypass = "luckypass.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["luckypass*"]
exclude = ["data*", "tests*"]